# -*- coding: utf-8 -*-
"""letsupgrade1stwork.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eWTR0ar4kDtYS1TnWvyLLwzkn-aNKKDR
"""

# using calculator for addition, subtraction, multiplication, division

a= int(input("first no"))
b= int(input("second no"))
add = a + b
sub = a - b
mul = a * b
div = a//b
print("addition", add)
print("subtraction", sub)
print("multiplication", mul)
print("division", div)